version: 1
validation: sovereign
default_denom: USDT
accounts: 
- name: alice
  coins:
  - 20000ATOM
  - 200000000USDT
- name: bob
  coins:
  - 10000ATOM
  - 100000000USDT
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5ATOM
  - 100000USDT
validators:
- name: alice
  bonded: 100000000USDT
- name: validator1
  bonded: 200000000USDT
- name: validator2
  bonded: 100000000USDT