version: 1
validation: sovereign
default_denom: uusdc
accounts: 
- name: alice
  coins:
  - 20000000000uatom
  - 20000000000uosmo
  - 200000000000uusdc
- name: bob
  coins:
  - 10000000000uatom
  - 10000000000uosmo
  - 100000000000uusdc
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5000000uatom
  - 5000000uosmo
  - 100000000uusdc
validators:
- name: alice
  bonded: 100000000uusdc
- name: validator1
  bonded: 200000000uusdc
- name: validator2
  bonded: 100000000uusdc
