package types

import (
	"encoding/hex"
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestTradeProofVerifierRejectsWhenVKMissing(t *testing.T) {
	verifier := NewTradeProofVerifier(map[string]string{TradeVerifierVKID: ""})
	update := tradeVerifierUpdate{PublicInputs: validTradeVerifierPublicInputs()}
	updateJSON, err := json.Marshal(update)
	require.NoError(t, err)

	bundle := tradeProofBundle{
		Proof:        "0x" + strings.Repeat("00", 128),
		PublicInputs: update.PublicInputs,
		VKID:         TradeVerifierVKID,
	}
	bundleJSON, err := json.Marshal(bundle)
	require.NoError(t, err)

	require.False(t, verifier.VerifyProof(updateJSON, bundleJSON))
}

func TestDefaultProofVerifierLoadsEmbeddedTradeVK(t *testing.T) {
	verifier, ok := DefaultProofVerifier().(TradeProofVerifier)
	require.True(t, ok)
	require.Contains(t, verifier.verifyingKeys, TradeVerifierVKID)
	require.Len(t, GazkTradeV1VerifyingKeyHex, 1178)
}

func TestTradeProofVerifierAcceptsRealGazkProofAndRejectsTamper(t *testing.T) {
	update := tradeVerifierUpdate{PublicInputs: realGazkTradePublicInputs()}
	updateJSON, err := json.Marshal(update)
	require.NoError(t, err)

	bundle := tradeProofBundle{
		Proof:             realGazkTradeProof,
		PublicInputs:      update.PublicInputs,
		VerificationKeyID: TradeVerifierVKID,
	}
	bundleJSON, err := json.Marshal(bundle)
	require.NoError(t, err)

	verifier := DefaultProofVerifier()
	require.True(t, verifier.VerifyProof(updateJSON, bundleJSON))

	tamperedInputs := realGazkTradePublicInputs()
	tamperedInputs[7] = "0x" + strings.Repeat("00", 32)
	tamperedBundle := bundle
	tamperedBundle.PublicInputs = tamperedInputs
	tamperedBundleJSON, err := json.Marshal(tamperedBundle)
	require.NoError(t, err)
	require.False(t, verifier.VerifyProof(updateJSON, tamperedBundleJSON))

	fakeProofBundle := bundle
	fakeProofBundle.Proof = "0x" + strings.Repeat("00", 128)
	fakeProofBundleJSON, err := json.Marshal(fakeProofBundle)
	require.NoError(t, err)
	require.False(t, verifier.VerifyProof(updateJSON, fakeProofBundleJSON))
}

func TestTradeProofVerifierRejectsPublicInputMismatch(t *testing.T) {
	verifier := NewTradeProofVerifier(map[string]string{TradeVerifierVKID: "0x00"})
	update := tradeVerifierUpdate{PublicInputs: validTradeVerifierPublicInputs()}
	updateJSON, err := json.Marshal(update)
	require.NoError(t, err)

	bundleInputs := validTradeVerifierPublicInputs()
	bundleInputs[1] = "0x" + strings.Repeat("ff", 32)
	bundle := tradeProofBundle{
		Proof:        "0x" + strings.Repeat("00", 128),
		PublicInputs: bundleInputs,
		VKID:         TradeVerifierVKID,
	}
	bundleJSON, err := json.Marshal(bundle)
	require.NoError(t, err)

	require.False(t, verifier.VerifyProof(updateJSON, bundleJSON))
}

func TestTradeProofVerifierUsesDefaultTradeVKIDWhenBundleOmitsID(t *testing.T) {
	verifier := NewTradeProofVerifier(map[string]string{TradeVerifierVKID: ""})
	update := tradeVerifierUpdate{PublicInputs: validTradeVerifierPublicInputs()}
	updateJSON, err := json.Marshal(update)
	require.NoError(t, err)

	bundle := tradeProofBundle{
		Proof:        "0x" + strings.Repeat("00", 128),
		PublicInputs: update.PublicInputs,
	}
	bundleJSON, err := json.Marshal(bundle)
	require.NoError(t, err)

	require.False(t, verifier.VerifyProof(updateJSON, bundleJSON))
}

func TestBuildTradePublicWitnessUsesEightInputs(t *testing.T) {
	w, err := buildTradePublicWitness(validTradeVerifierPublicInputs())
	require.NoError(t, err)
	publicW, err := w.Public()
	require.NoError(t, err)
	require.Len(t, publicW.Vector(), tradePublicInputCount)
}

func TestBuildTradePublicWitnessRejectsBadHex(t *testing.T) {
	publicInputs := validTradeVerifierPublicInputs()
	publicInputs[0] = "0xnothex"

	_, err := buildTradePublicWitness(publicInputs)
	require.Error(t, err)
}

func validTradeVerifierPublicInputs() []string {
	inputs := make([]string, tradePublicInputCount)
	for i := range inputs {
		inputs[i] = "0x" + hex.EncodeToString([]byte{
			byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i),
			byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i),
			byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i),
			byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i), byte(i),
		})
	}
	return inputs
}

// realGazkTradeProof and realGazkTradePublicInputs are the proof/publicInputs
// fields from gazk-trade-v1.interop-vector.json, generated by the gazk key store
// whose verifyingKey is embedded as GazkTradeV1VerifyingKeyHex. Regenerate both
// together whenever the trade circuit changes.
const realGazkTradeProof = "0x82ee3857c84527cffc0b4736d3458b4ef6ce20d9ed8d65586cd2f0be0dc5938c9419f186f091a3c1365f818c8cee5bb2eead225b725de63a3cb6287fe5c049340a417ad9ea2abec5f8fdd0e55b0e263307be4bc2294417454e068ad5d9a49790a69758ee24a64e5eb23b0bab7274640b0bae342cbc0e97c3586977c8cabe3181000000004000000000000000000000000000000000000000000000000000000000000000"

func realGazkTradePublicInputs() []string {
	return []string{
		"0xdc03bee69322b6f860de17cc11d8bee7e5cc41ae22e72d3da1065fe8d13db103",
		"0xc79bc87c5df4b3cf94560d58f19f2b36631b93a60132efd0c61ac8b474069e61",
		"0x0d5927e78698013a0fd5f14aa2e4a5839f76b72b6c66ccfc0f4d82e54514f6ee",
		"0x254d20a0127f09e171a08cb3989c1226f9342586d5c1b14bac101bc1a4a5a7e4",
		"0x0fbda30e91ff91a81172d80bd6ddea3357cc9792740ed401ae03bf4bb6b49580",
		"0x1b61e64bfdfd5dab18034894d36fc218dedf961eaf097af54f03dd088c60a8b2",
		"0xe0485ea21f6ea846a9de81a4153afa85ca471933f6910285258c0c2051410dfb",
		"0x798b004fcf98281e699899cf89b853a5849bf8e8fdbf474b7300e770cd4ab3ea",
	}
}
